title: "NBME - Score Clinical Patient Notes"
description: >
  TODO.

vars:
  train_splits: "train_split.json.gz"
  case_num: 0
  feature_num: 0
  train: "train-case_num-${vars.case_num}-feature_num-${vars.feature_num}"
  dev: "dev-case_num-${vars.case_num}-feature_num-${vars.feature_num}"
  test: "test-case_num-${vars.case_num}-feature_num-${vars.feature_num}"
  config: "config.cfg"

directories: ["configs", "corpus", "input", "scripts", "training"]

assets:
  - dest: "input/nbme-score-clinical-patient-notes/${vars.train_splits}"

workflows:
  all:
    - preprocess
    - debug
    - train

commands:
  - name: "preprocess"
    help: "Convert the data to spaCy's binary format"
    script:
      - "python scripts/preprocess.py input/nbme-score-clinical-patient-notes corpus ${vars.case_num} ${vars.feature_num}"
    deps:
      - "input/nbme-score-clinical-patient-notes/${vars.train_splits}"
      - "scripts/preprocess.py"
    outputs:
      - "corpus/${vars.train}.spacy"
      - "corpus/${vars.dev}.spacy"
      - "corpus/${vars.test}.spacy"

  - name: "debug"
    help: "Debug the data"
    deps:
      - "corpus/${vars.train}.spacy"
      - "corpus/${vars.dev}.spacy"
      - "corpus/${vars.test}.spacy"
    script:
      - python -m spacy debug data configs/${vars.config}  --paths.train corpus/${vars.train}.spacy --paths.dev corpus/${vars.dev}.spacy --paths.test corpus/${vars.test}.spacy

  - name: "train"
    help: "Train a custom NER model"
    script:
      - "python -m spacy train configs/${vars.config} --output training/ --paths.train corpus/${vars.train}.spacy --paths.dev corpus/${vars.dev}.spacy # --code scripts/custom_functions.py"
    deps:
      - "corpus/${vars.train}.spacy"
      - "corpus/${vars.dev}.spacy"
    outputs:
      - "training/model-best"